### ISSUE TITLE
[TensorFlow -> ONNX] BiasAdd layer after DepthwiseConv2dNative is ommited

### ISSUE THREAD

**Issue by mciprian13** [microsoft/MMdnn#792] opened 2020-02-25 08:12 UTC
Platform (like ubuntu 16.04/win10): **Win10**
Python version: **Python 3.6.4**
Source framework with version (like Tensorflow 1.4.1 with GPU): **tensorflow 1.14.0**
Destination framework with version (like CNTK 2.3 with GPU): **onnx 1.5.0**
Pre-trained model path (webpath or webdisk path):
https://github.com/ARM-software/ML-KWS-for-MCU/blob/master/Pretrained_models/DS_CNN/DS_CNN_L.pb

Running scripts:
`mmconvert                                     
  --srcFramework tensorflow                   
  --inputWeight DS_CNN_L.pb                   
  --inNodeName Reshape_1                      
  --inputShape 49,10,1                        
  --dstNodeName labels_softmax               
  --dstFramework onnx                        
  --outputModel DS_CNN_L_mmdnn.onnx
`

When converting the above model, where the following groups are encountered (TensorFlow pb):
![image](https://user-images.githubusercontent.com/29785908/75227380-c17bc580-57b6-11ea-8c0e-cda055d9b4dd.png)

the **BiasAdd** layer is ommited and the resulting layer is this (ONNX):

![image](https://user-images.githubusercontent.com/29785908/75227437-dc4e3a00-57b6-11ea-89c2-81264afc8325.png)

You can see the bias operand of the convolution (**B**) is missing.
I actually verified the numerical behavior of the resulting ONNX model is NOT correct (using some actual input data and comparing to the original TensorFlow model).
I manually edited the ONNX proto in order to put the missing bias operands, after which the numerical behavior became correct.

**Comment by linmajia** [comment] 2020-03-09 03:26
@mciprian13 , thank you very much for the feedback. We will look into the issue.

**Comment by linmajia** [comment] 2020-03-13 16:29
@mciprian13 , it seems that function rename_DepthwiseConv2dNative() forgets to handle the BiasAdd. You may take the following workaround:
1. Go to the installation directory of MMdnn. E.g.  ~/.local/lib/pythonX.Y/site-packages/mmdnn , or /usr/lib/python3/dist-packages/mmdnn
2. Open file "conversion/tensorflow/tensorflow_frozenparser.py" .
2. Locate the rename_DepthwiseConv2dNative() function.
3. Add "self._get_bias(source_node, IR_node)" to the end.

Please have a try and verify whether the issue is fixed.

Thanks.

**Comment by linmajia** [comment] 2020-03-15 23:28
Fixed in the pull request https://github.com/microsoft/MMdnn/pull/800.

**Closed by linmajia** 2020-03-15 23:28 UTC
Labels: bug
