### ISSUE TITLE
tensorflow to caffe LRN

### ISSUE THREAD

**Issue by hnuhchen** [microsoft/MMdnn#805] opened 2020-03-18 08:52 UTC
Platform (like ubuntu 16.04/win10):
ubuntu 16.04
Python version:
python3.5.2
Source framework with version (like Tensorflow 1.4.1 with GPU):
tensorflow
Destination framework with version (like CNTK 2.3 with GPU):
caffe
Pre-trained model path (webpath or webdisk path):

Running scripts:

Hello,everyone.
here is code in tensorflow_parser.py and caffe_emitter.py
```
def rename_LRN(self,   source_node):

    IR_node = self._convert_identity_operation(source_node)
    kwargs = {
    "alpha" : source_node.get_attr('alpha') * (source_node.get_attr('depth_radius') * 2 + 1),
    "beta" : source_node.get_attr('beta'),
    "bias" : source_node.get_attr('bias'),
    'size' : source_node.get_attr('depth_radius') + 1
    }
    assign_IRnode_values(IR_node, kwargs)
```

```
def emit_LRN(self,   IR_node):

    self.add_body(1, "n.{:<15}   = L.LRN(n.{}, local_size={}, alpha={}, beta={}, k={})".format(
    IR_node.variable_name,
    self.parent_variable_name(IR_node),
    IR_node.get_attr('size') * 2 - 1,
    IR_node.get_attr('alpha'),
    IR_node.get_attr('beta'),
    IR_node.get_attr('k')
    ))
```

So, what is k? or bias?

**Comment by linmajia** [comment] 2020-03-19 02:18
@hnuhchen , thank you very much for the feedback. Different DL frameworks have different naming of this parameter. E.g., it is called "bias" in [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/nn/local_response_normalization) and [ONNX](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LRN). However, it is called "knorm" in [MXNet](http://beta.mxnet.io/r/api/mx.symbol.LRN.html) and simply "k" in [Caffe](https://caffe.berkeleyvision.org/tutorial/layers/lrn.html).

This parameter is defined as "bias" in MMdnn's [unified IR](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/common/IR/ops.pbtxt#L765). So the issue is a bug that we misused the parameter name. We will fix it soon.

**Comment by linmajia** [comment] 2020-03-25 00:46
Fixed in https://github.com/microsoft/MMdnn/pull/807

**Closed by linmajia** 2020-03-25 00:46 UTC
Labels: bug
