### ISSUE TITLE
'mmdownload' is not an internal or external command

### ISSUE THREAD

**Issue by shiningdsr** [microsoft/MMdnn#851] opened 2020-06-15 09:20 UTC
Platform (like ubuntu 16.04/win10):win10

Python version:3.7.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.13.1 with GPU

Destination framework with version (like CNTK 2.3 with GPU): Keras 2.2.4

Pre-trained model path (webpath or webdisk path):

Running scripts: mmdownload -f keras -n resnet50
'mmdownload' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by linmajia** [comment] 2020-06-15 13:16
Duplicate of #852

**Closed by linmajia** 2020-06-15 13:16 UTC
